config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources 'pins' do
    resources :comments
    member do
      put "like", to:"pins#upvote"
    end
  end

root 'pins#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, presence:true ,length: {minimum: 3 }
  validates :comment, presence:true ,length: {minimum: 3}
  belongs_to :user
  belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many  :comments, dependent: :destroy
  has_attached_file :image, styles:{medium:"300x300>"}
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
    @pin= Pin.find(params[:pin_id])
    @comment=@pin.comments.create(params[:comment].permit(:name, :comment))
    redirect_to pin_path(@pin, errors: @comment.errors.messages)
  end

  def edit
    @pin= Pin.find(params[:pin_id])
    @comment=Comment.find(params[:id])
  end

  def update
    @pin= Pin.find(params[:pin_id])
    @comment=@pin.comments.find(params[:id])
    if @comment.update(params[:comment].permit(:name, :comment))
      redirect_to @comment.pin if @comment.save
    else
      redirect_to :back
    end
  end

  def destroy
    @pin= Pin.find(params[:pin_id])
    @comment=@pin.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
before_action :find_pin, only: [:show, :edit, :update, :destroy,:upvote]
before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins=Pin.all.order("created_at DESC")
  end

  def new
    @pin=current_user.pins.build
  end

  def create
    @pin=current_user.pins.build(pin_params)
    if @pin.save
       flash[:success] = "Pin Successfully created!"
      redirect_to @pin
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    if params[:errors]
      params[:errors].each do |name, message|
        message.each do |msg|
          @comment.errors.add(name.to_sym, msg)
        end
      end
    end
  end

  def update
    if @pin.update(pin_params)
       flash[:success] = "Pin Successfully Updated!"
      redirect_to @pin
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    flash[:danger] = "Pin Successfully Deleted!"
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin=Pin.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment.comment_content
    .col-md-6
      .comment_comment
        =comment.comment
      .comment_name
        %small Submitted by
        %small= comment.name
      .comment_time
        %small Submitted
        %small= "#{time_ago_in_words(comment.created_at)} ago"
    .col-md-6
      .button.pull-right
        -if user_signed_in?
          =link_to "Delete",[comment.pin, comment],
                    method: :delete, class: "button", data:{ confirm: 'Are You Sure ?'}, class: "btn btn-default"
%br/

app/views/comments/_form.html.haml
= form_for ([@pin, @comment]) do |f|
  -if @comment.errors.any?
    #errors
      %h2= "#{pluralize(@comment.errors.count, "error")} prevented this comment from saving."
      %ul
        -@comment.errors.full_messages.each do|msg|
          %li= msg
  %p= f.label :name
  = f.text_field:name,class: "form-control"
  %p= f.label :comment
  = f.text_area :comment,class: "form-control"
  %br
  = f.submit

app/views/comments/edit.html.haml
= form_for [@post, @comment] do |f|
  %p= f.label :name
  %br
  = f.text_field:name
  %p= f.label :comment
  %br
  = f.text_area:comment
  %p= f.submit %br

app/views/layouts/_top.html.haml
.nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "Pin Board", root_path
    -if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "New Pin",new_pin_path
        %li= link_to "Account", edit_user_registration_path
        %li= link_to "Sign out",destroy_user_session_path, method: :delete
    -else
      %ul.nav.navbar-nav.navbar-right
        %li=link_to "Sign up",new_user_registration_path
        %li=link_to "Sign in",user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pin Board
  = favicon_link_tag 'favicon.ico'
  = stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  = render "layouts/top"
  .container
    -flash.each do |name,msg|
      =content_tag :div, msg , class: "alert alert-#{name}"
    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart:true} do |f|
  -if @pin.errors.any?
    #errors
    %h2
      = pluralize(@pin.errors.count, "Error")
      prevented this pin from saving
    %ul
      - @pin.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    =f.input :image, input_html: {class: 'form-control'}


  .form-group
    =f.input :title, input_html: {class: 'form-control'}

  .form-group
    =f.input :description, input_html: {class: 'form-control'}
  =f.button :submit,{class: 'btn btn-primary'}

app/views/pins/edit.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        %h1 Edit
        =image_tag @pin.image.url(:medium)
        =render 'form'
        %br/
        =link_to "Cancel", pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      %h2= link_to pin.title, pin
      %p.user
        Submitted by
        = pin.user.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Pin
  = render 'form'
  %br
  = link_to "Back",root_path

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        =image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %p= @pin.description
      .panel-footer
        .row
          .col-md-6
            %p.user
            Sumitted by:
            =@pin.user.email
          .col-md-6
            .btn-group.pull-right
              =link_to like_pin_path(@pin), method: :put, class: 'btn btn-default' do
                %span.glyphicon.glyphicon-heart
                  =@pin.get_upvotes.size
              -if user_signed_in?
                =link_to "Edit", edit_pin_path, class: 'btn btn-default'
                =link_to "Delete",@pin, class: 'btn btn-default', method: :delete, data: {confirm:"Are you sure ?"}
          .col-md-12
            %h4=pluralize(@pin.comments.count, "Comment")
            = render @pin.comments
            %h3= "Add a comment:"
            =render 'comments/form'